import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1773769107855 implements MigrationInterface {
    name = 'InitSchema1773769107855'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_location_certifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, "locationId" uuid NOT NULL, "certifiedAt" TIMESTAMP NOT NULL, "revokedAt" TIMESTAMP, "revokedBy" uuid, "revocationReason" text, CONSTRAINT "PK_fa76612b9eb867f3b730e54b89b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4f4ecb0b9332a9fa95cf2f1b0" ON "user_location_certifications" ("userId", "locationId") `);
        await queryRunner.query(`CREATE TABLE "skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying(100) NOT NULL, "description" text, CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_81f05095507fd84aa2769b4a52" ON "skills" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."shift_assignments_status_enum" AS ENUM('assigned', 'confirmed', 'swap_pending', 'dropped', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "shift_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "shiftId" uuid NOT NULL, "userId" uuid NOT NULL, "assignedBy" uuid NOT NULL, "status" "public"."shift_assignments_status_enum" NOT NULL, "assignedByUserId" uuid, CONSTRAINT "PK_7a78d24f38deedd9fe0ea19685c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_647779813dec7e65a4f57bf878" ON "shift_assignments" ("shiftId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8391cc66ec187e5f13c715311b" ON "shift_assignments" ("userId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."shifts_status_enum" AS ENUM('draft', 'published', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "locationId" uuid NOT NULL, "requiredSkillId" uuid NOT NULL, "title" character varying(255), "startAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endAt" TIMESTAMP WITH TIME ZONE NOT NULL, "headcountNeeded" smallint NOT NULL DEFAULT '1', "status" "public"."shifts_status_enum" NOT NULL DEFAULT 'draft', "publishedAt" TIMESTAMP WITH TIME ZONE, "editCutoffHours" smallint NOT NULL DEFAULT '48', "isPremium" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_18075d5e76b464baf104291180" ON "shifts" ("startAt", "endAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b776467a29eb83e05b5e8d0ecf" ON "shifts" ("locationId", "startAt", "status") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "actorId" uuid, "entityType" character varying(100) NOT NULL, "entityId" uuid NOT NULL, "action" character varying(100) NOT NULL, "beforeState" jsonb, "afterState" jsonb, "ipAddress" character varying(45), "userAgent" text, "locationId" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_51fa2190a08765420d8f32c4df" ON "audit_logs" ("locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2dc33f7f3c22e2e7badafca1d1" ON "audit_logs" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "name" character varying(255) NOT NULL, "address" text, "ianaTimezone" character varying(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "availability_windows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, "dayOfWeek" smallint NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "effectiveFrom" date NOT NULL, "effectiveUntil" date, CONSTRAINT "PK_2b90591d83bf13eb2a2667d49ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39d2c9fc59f67ee81e71ecbc2e" ON "availability_windows" ("userId", "dayOfWeek") `);
        await queryRunner.query(`CREATE TABLE "availability_exceptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, "exceptionDate" date NOT NULL, "isAvailable" boolean NOT NULL, "startTime" TIME, "endTime" TIME, "reason" text, CONSTRAINT "PK_f5a89a7a6221bc93b517a13351f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."swap_requests_type_enum" AS ENUM('swap', 'drop')`);
        await queryRunner.query(`CREATE TYPE "public"."swap_requests_status_enum" AS ENUM('pending_target', 'pending_manager', 'approved', 'rejected', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "swap_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "initiatorId" uuid NOT NULL, "targetUserId" uuid, "initiatorAssignmentId" uuid NOT NULL, "targetAssignmentId" uuid, "type" "public"."swap_requests_type_enum" NOT NULL, "status" "public"."swap_requests_status_enum" NOT NULL, "initiatorNote" text, "targetNote" text, "managerNote" text, "reviewedBy" uuid, "reviewedAt" TIMESTAMP, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_4a3a8b292e0e8df37acbc47e648" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d7b5bab26159b700111213c9d" ON "swap_requests" ("targetUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2fdf3102ce48dfad9a0bccde77" ON "swap_requests" ("initiatorId") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, "type" character varying(100) NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "referenceType" character varying(100), "referenceId" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_21e65af2f4f242d4c85a92aff4" ON "notifications" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "revokedAt" TIMESTAMP, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'manager', 'staff')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "email" character varying(255) NOT NULL, "passwordHash" character varying NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "phone" character varying(20), "role" "public"."users_role_enum" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "desiredHoursPerWeek" numeric(5,2), "notifyInApp" boolean NOT NULL DEFAULT true, "notifyEmail" boolean NOT NULL DEFAULT false, "lastLoginAt" TIMESTAMP, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "manager_location_assignments" ("locationId" uuid NOT NULL, "managerId" uuid NOT NULL, CONSTRAINT "PK_262972cdd7960280d4017e1d92f" PRIMARY KEY ("locationId", "managerId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_510fb839c8afaf3147c994719a" ON "manager_location_assignments" ("locationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8c4694bb9597296e150b1c331" ON "manager_location_assignments" ("managerId") `);
        await queryRunner.query(`CREATE TABLE "user_skills" ("userId" uuid NOT NULL, "skillId" uuid NOT NULL, CONSTRAINT "PK_060bea7fd45868588324719de3c" PRIMARY KEY ("userId", "skillId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_60177dd93dcdc055e4eaa93bad" ON "user_skills" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b19f190afaada3852e0f56566b" ON "user_skills" ("skillId") `);
        await queryRunner.query(`ALTER TABLE "user_location_certifications" ADD CONSTRAINT "FK_980c87b22e379475be3e74ebded" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_location_certifications" ADD CONSTRAINT "FK_b9dc39bbe7e04a028db3f8cbfdb" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD CONSTRAINT "FK_647779813dec7e65a4f57bf878f" FOREIGN KEY ("shiftId") REFERENCES "shifts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD CONSTRAINT "FK_081820c9155a7380c6850d3d9b0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" ADD CONSTRAINT "FK_35b1df8c2983b04ff23f03f941e" FOREIGN KEY ("assignedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_3d99162b7f0bf354d34c098413f" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_a4fe983af7cffcd6e273368aeca" FOREIGN KEY ("requiredSkillId") REFERENCES "skills"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_2dc33f7f3c22e2e7badafca1d12" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_51fa2190a08765420d8f32c4dfe" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_windows" ADD CONSTRAINT "FK_56eb6da280881e885420f2f05ae" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "availability_exceptions" ADD CONSTRAINT "FK_fbbe0f3165faab589145416c2b5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_requests" ADD CONSTRAINT "FK_2fdf3102ce48dfad9a0bccde776" FOREIGN KEY ("initiatorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_requests" ADD CONSTRAINT "FK_7d7b5bab26159b700111213c9d1" FOREIGN KEY ("targetUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_requests" ADD CONSTRAINT "FK_09d38cb0b4b8592f04f243ef9e1" FOREIGN KEY ("initiatorAssignmentId") REFERENCES "shift_assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap_requests" ADD CONSTRAINT "FK_f49aa4543c34c10dc0b8a347fe4" FOREIGN KEY ("targetAssignmentId") REFERENCES "shift_assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "manager_location_assignments" ADD CONSTRAINT "FK_510fb839c8afaf3147c994719ae" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "manager_location_assignments" ADD CONSTRAINT "FK_b8c4694bb9597296e150b1c3317" FOREIGN KEY ("managerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_skills" ADD CONSTRAINT "FK_60177dd93dcdc055e4eaa93bade" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_skills" ADD CONSTRAINT "FK_b19f190afaada3852e0f56566bc" FOREIGN KEY ("skillId") REFERENCES "skills"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_skills" DROP CONSTRAINT "FK_b19f190afaada3852e0f56566bc"`);
        await queryRunner.query(`ALTER TABLE "user_skills" DROP CONSTRAINT "FK_60177dd93dcdc055e4eaa93bade"`);
        await queryRunner.query(`ALTER TABLE "manager_location_assignments" DROP CONSTRAINT "FK_b8c4694bb9597296e150b1c3317"`);
        await queryRunner.query(`ALTER TABLE "manager_location_assignments" DROP CONSTRAINT "FK_510fb839c8afaf3147c994719ae"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "swap_requests" DROP CONSTRAINT "FK_f49aa4543c34c10dc0b8a347fe4"`);
        await queryRunner.query(`ALTER TABLE "swap_requests" DROP CONSTRAINT "FK_09d38cb0b4b8592f04f243ef9e1"`);
        await queryRunner.query(`ALTER TABLE "swap_requests" DROP CONSTRAINT "FK_7d7b5bab26159b700111213c9d1"`);
        await queryRunner.query(`ALTER TABLE "swap_requests" DROP CONSTRAINT "FK_2fdf3102ce48dfad9a0bccde776"`);
        await queryRunner.query(`ALTER TABLE "availability_exceptions" DROP CONSTRAINT "FK_fbbe0f3165faab589145416c2b5"`);
        await queryRunner.query(`ALTER TABLE "availability_windows" DROP CONSTRAINT "FK_56eb6da280881e885420f2f05ae"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_51fa2190a08765420d8f32c4dfe"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_2dc33f7f3c22e2e7badafca1d12"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_a4fe983af7cffcd6e273368aeca"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_3d99162b7f0bf354d34c098413f"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP CONSTRAINT "FK_35b1df8c2983b04ff23f03f941e"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP CONSTRAINT "FK_081820c9155a7380c6850d3d9b0"`);
        await queryRunner.query(`ALTER TABLE "shift_assignments" DROP CONSTRAINT "FK_647779813dec7e65a4f57bf878f"`);
        await queryRunner.query(`ALTER TABLE "user_location_certifications" DROP CONSTRAINT "FK_b9dc39bbe7e04a028db3f8cbfdb"`);
        await queryRunner.query(`ALTER TABLE "user_location_certifications" DROP CONSTRAINT "FK_980c87b22e379475be3e74ebded"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b19f190afaada3852e0f56566b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60177dd93dcdc055e4eaa93bad"`);
        await queryRunner.query(`DROP TABLE "user_skills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8c4694bb9597296e150b1c331"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_510fb839c8afaf3147c994719a"`);
        await queryRunner.query(`DROP TABLE "manager_location_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21e65af2f4f242d4c85a92aff4"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fdf3102ce48dfad9a0bccde77"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d7b5bab26159b700111213c9d"`);
        await queryRunner.query(`DROP TABLE "swap_requests"`);
        await queryRunner.query(`DROP TYPE "public"."swap_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."swap_requests_type_enum"`);
        await queryRunner.query(`DROP TABLE "availability_exceptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39d2c9fc59f67ee81e71ecbc2e"`);
        await queryRunner.query(`DROP TABLE "availability_windows"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dc33f7f3c22e2e7badafca1d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51fa2190a08765420d8f32c4df"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b776467a29eb83e05b5e8d0ecf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18075d5e76b464baf104291180"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP TYPE "public"."shifts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8391cc66ec187e5f13c715311b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_647779813dec7e65a4f57bf878"`);
        await queryRunner.query(`DROP TABLE "shift_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."shift_assignments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81f05095507fd84aa2769b4a52"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4f4ecb0b9332a9fa95cf2f1b0"`);
        await queryRunner.query(`DROP TABLE "user_location_certifications"`);
    }

}
