services:
  frontend:
    build: ./shiftsync-web
    ports:
      - "3000:3000"
    env_file:
      - ./shiftsync-web/.env
    volumes:
      - ./shiftsync-web:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./shiftsync-api
    ports:
      - "4000:4000"
    env_file:
      - ./shiftsync-api/.env
    volumes:
      - ./shiftsync-api:/usr/src/app
      - /usr/src/app/node_modules