export const NotificationType = {
  SHIFT_ASSIGNED: 'shift.assigned',
  SHIFT_CHANGED: 'shift.changed',
  SHIFT_CANCELLED: 'shift.cancelled',
  SCHEDULE_PUBLISHED: 'schedule.published',
  SWAP_REQUEST_RECEIVED: 'swap.request_received',
  SWAP_ACCEPTED: 'swap.accepted',
  SWAP_REJECTED: 'swap.rejected',
  SWAP_APPROVED: 'swap.approved',
  SWAP_DENIED: 'swap.denied',
  SWAP_CANCELLED: 'swap.cancelled',
  SWAP_EXPIRED: 'swap.expired',
  DROP_REQUEST_RECEIVED: 'drop.request_received',
  DROP_PICKED_UP: 'drop.picked_up',
  DROP_EXPIRED: 'drop.expired',
  OVERTIME_WARNING: 'overtime.warning',
  OVERTIME_EXCEEDED: 'overtime.exceeded',
  AVAILABILITY_CHANGED: 'availability.changed',
  CONSECUTIVE_DAY_WARNING: 'consecutive_day.warning',
} as const;
